### ISSUE TITLE
Can i use it as a `buildModules`?

### ISSUE THREAD

**Issue by LuXDAmore** [robcresswell/nuxt-compress#14]
Nuxt v2.9 suggest to use '_static modules_' as **build modules**..
It's possible with this one?

[Read here](https://nuxtjs.org/guide/modules/#build-only-modules) - [and here](https://nuxtjs.org/api/configuration-modules#-code-buildmodules-code-)

**Comment by robcresswell** [comment]
Perhaps you could test it and let me know?

**Comment by LuXDAmore** [comment]
Yes, it's possible and i think it's the suggested way 🚀 

Can i open a PR to update the README file with this advice?

**Comment by robcresswell** [comment]
Please do :smile:

**Comment by LuXDAmore** [comment]
@robcresswell Done [PR](https://github.com/robcresswell/nuxt-compress/pull/15)

**Comment by azrikahar** [comment]
@robcresswell I believe we can close this issue now with the merging of #15 earlier today. Thanks @LuXDAmore !

**Comment by robcresswell** [comment]
Good point, closed

**Comment by LuXDAmore** [comment]
Thank You!!

@azrikahar @robcresswell
