### ISSUE TITLE
Issue while running on local machine

### ISSUE THREAD

**Issue by rajeevp** [robcresswell/nuxt-compress#33]
I have configured this module and using nuxt build command to generate the build. Output is as expected generated in dist folder. But when I run the application using nuxt start, my request never gets serve. It gives me following issue:
<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF77A84538F napi_wrap+114751
 2: 00007FF77A7EFE26 v8::base::CPU::has_sse+66646
 3: 00007FF77A7F0C26 v8::base::CPU::has_sse+70230
 4: 00007FF77B005B3E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF77AFEDC11 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF77AEB9E7C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF77AEC50B0 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF77AEC1BD4 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF77AEB73D3 v8::internal::Heap::CollectGarbage+1283
10: 00007FF77AEB9FCA v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1770
11: 00007FF77AEB0593 v8::base::CPU::has_vfp3+467
12: 00007FF77A7881AF std::basic_ostream<char,std::char_traits<char> >::operator<<+71055
13: 00007FF77A787214 std::basic_ostream<char,std::char_traits<char> >::operator<<+67060
14: 00007FF77A8954FB uv_async_send+331
15: 00007FF77A894C9C uv_loop_init+1212
16: 00007FF77A894E64 uv_run+244
17: 00007FF77A7A68E1 v8::internal::UnoptimizedCompilationInfo::feedback_vector_spec+31857
18: 00007FF77A819963 node::Start+275
19: 00007FF77A686A9C RC4_options+340380
20: 00007FF77B512188 v8::internal::SetupIsolateDelegate::SetupHeap+1300536
21: 00007FFD2FFD84D4 BaseThreadInitThunk+20
22: 00007FFD3250E871 RtlUserThreadStart+33

This seems to me more nuxt start command issue not this plugin issue. Just to double check.

**Comment by robcresswell** [comment]
If you remove the plugin, does the issue still occur?

**Comment by rajeevp** [comment]
No, it is not. 
BTW I am using universal nuxt app. Will there be any issue with compression?

I am using alterative now, using nginx reverse-proxy and using gzip compression.

**Comment by robcresswell** [comment]
I don't really know. If you can push a minimal reproduction somewhere for me to look at I'll investigate.
