### ISSUE TITLE
Suggestion: Highlight the advantage of nuxt-compress compare to the normal compression system used by Nuxt

### ISSUE THREAD

**Issue by trollepierre** [robcresswell/nuxt-compress#39]
If I add nuxt-compress , what will be the advantage over https://www.npmjs.com/package/compression already set in [nuxt](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-render#compressor) 

Could it be possible to add this in the Readme, in order to make it clear for next visitor interesting by this package

thanks ;-)

**Comment by robcresswell** [comment]
The first two lines of the README explain what the difference is. The compression middleware is at runtime, but this is during build time, so there's no runtime performance hit from compressing.

**Comment by trollepierre** [comment]
Ok I got it better.

I don't understand why the Core Team of Nuxt is not using nuxt-compress by default, in that case.

"Using nuxt-compress at build time and then, the compression middleware." => should be a feature in Nuxt

**Comment by robcresswell** [comment]
Maybe. It's hard to draw the line between plugins and core. This is a really tiny plugin so I'm happy to maintain it.
