### ISSUE TITLE
Nuxt not using compressed files

### ISSUE THREAD

**Issue by ghost** [robcresswell/nuxt-compress#5]
Hello. I don't know if this is a problem of this library, but I'll ask anyway.

The compressed bundle files are generated as they should, but nuxt does'nt use them. The files in the served html pages are the js-files.

Am I missing some configuration, or something else?

**Comment by Ic3m4n34** [comment]
Hi @tuomasinkinen 
How did you solve this? I have the same issue. I'd appreciate your help

**Comment by ghost** [comment]
Hi @Ic3m4n34 
I think this was really not a problem, since it's the role of some web server to serve those compressed files, not nuxt's.

I can't remember very accurately, this was so long ago, but I have a strong feeling that my question itself was stupid :)

**Comment by Ic3m4n34** [comment]
@tuomasinkinen Thanks for your answer. I think you're right. I now solved this via Netlify. So my question regarding your questions is stupid as well and this issue can remain closed. Thanks again 🙂
